# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quickview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=20)),
                ('OneLiner', models.CharField(max_length=500)),
                ('WebsiteUrl', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Quickview',
            },
        ),
        migrations.DeleteModel(
            name='Ico',
        ),
    ]
