# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171005_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickview',
            name='CompanyName',
            field=models.CharField(max_length=200),
        ),
    ]
