# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171005_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickview',
            name='IcoStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='Logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quickview',
            name='CompanyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quickview',
            name='OneLiner',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quickview',
            name='WebsiteUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
