# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171005_1110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quickview',
            table='Quickviews',
        ),
    ]
