# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171005_1126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quickview',
            table='Quickview',
        ),
    ]
