# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171006_0017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quickview',
            table='SelectIcos("")',
        ),
    ]
