# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171006_0019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quickview',
            table='Quickview',
        ),
    ]
