# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171006_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'IcoDetails',
            },
        ),
        migrations.CreateModel(
            name='QuickviewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Quickview',
            },
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='IcoStart',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='Logo',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='OneLiner',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='WebsiteUrl',
        ),
    ]
