# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171012_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickviewCount',
        ),
    ]
