# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_quickviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='icodetails',
            name='AcceptedCurrency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='CompanyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='CountryofOrigin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='Description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='ExpectedCurrency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='HypeScore',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoPhase',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoScale',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoSymbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoTotalExpected',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='IcoTotalRaised',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='InvestmentPotential',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='Logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='OneLiner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='OverallRating',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='RaisedCurrency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='RiskScore',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='ScaleCurrency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='TechnoDetails',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='TokenDistribution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='TokenSales',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='TotalCurrency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='UnderlayingTechno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='WebsiteUrl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='icodetails',
            name='YearofOrigin',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='CompanyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='IcoEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='IcoId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='IcoStart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='Logo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='OneLiner',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quickview',
            name='WebsiteUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
