# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171012_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IcoId', models.CharField(max_length=10, null=True)),
                ('Type', models.CharField(max_length=20, null=True)),
                ('Title', models.CharField(max_length=1000, null=True)),
                ('Link', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'SocialArticles',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IcoId', models.CharField(max_length=10, null=True)),
                ('Type', models.CharField(max_length=20, null=True)),
                ('Link', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'SocialLinks',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IcoId', models.CharField(max_length=10, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Position', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'TeamMember',
            },
        ),
    ]
