# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_socialarticles_sociallinks_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialarticles',
            name='IcoDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SocialArticles', to='api.IcoDetails'),
        ),
    ]
