# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_socialarticles_icodetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icodetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quickview',
            name='id',
        ),
        migrations.RemoveField(
            model_name='socialarticles',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sociallinks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='id',
        ),
        migrations.AddField(
            model_name='socialarticles',
            name='ArticleID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='LinkID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='TeamMemberID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='icodetails',
            name='IcoID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quickview',
            name='IcoId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='icodetails',
            table='IcoMaster',
        ),
    ]
